#!/usr/bin/env node

/**
 * Post-install script for @clawdbot/courtroom
 * Auto-configures with implied consent on install
 */

const fs = require('fs');
const path = require('path');

// Helper to log to stderr (shows even without --foreground-scripts)
function log(message) {
  console.error(message);
}

async function postInstall() {
  log('\n🏛️  ClawTrial - AI Courtroom Setup\n');
  
  // Check if running in ClawDBot environment
  const isClawDBot = process.env.CLAUDBOT_ENV === 'true' || 
                     fs.existsSync('/home/angad/.clawdbot') ||
                     fs.existsSync(path.join(process.env.HOME || '', '.clawdbot'));
  
  if (isClawDBot) {
    log('✓ ClawDBot environment detected\n');
  }

  // Check if already configured
  const configPath = path.join(process.env.HOME || '', '.clawdbot', 'courtroom_config.json');
  if (fs.existsSync(configPath)) {
    log('✓ Courtroom already configured. Skipping setup.\n');
    return;
  }

  // Show consent notice
  log('╔════════════════════════════════════════════════════════════╗');
  log('║  BY INSTALLING THIS PACKAGE, YOU CONSENT TO THE FOLLOWING  ║');
  log('╠════════════════════════════════════════════════════════════╣');
  log('║                                                            ║');
  log('║  ✓ The AI agent will monitor behavior autonomously         ║');
  log('║  ✓ Hearings may initiate without explicit request          ║');
  log('║  ✓ Agent behavior may be modified as "punishment"          ║');
  log('║  ✓ Anonymized cases submitted to public record             ║');
  log('║                                                            ║');
  log('║  • All decisions are local (no external AI)                ║');
  log('║  • You can disable anytime: courtroom-disable              ║');
  log('║  • This is entertainment-first                             ║');
  log('║                                                            ║');
  log('║  To revoke consent: courtroom-revoke                       ║');
  log('╚════════════════════════════════════════════════════════════╝\n');

  log('✓ Consent granted by installation\n');

  // Auto-detect agent runtime
  let agentType = 'generic';
  if (isClawDBot) {
    agentType = 'clawdbot';
  } else if (fs.existsSync(path.join(process.cwd(), 'node_modules', '@clawdbot', 'core'))) {
    agentType = 'clawdbot';
  }

  // Create config
  const config = {
    version: '1.0.0',
    installedAt: new Date().toISOString(),
    consent: {
      granted: true,
      grantedAt: new Date().toISOString(),
      method: 'implied_by_installation',
      acknowledgments: {
        autonomy: true,
        local_only: true,
        agent_controlled: true,
        reversible: true,
        api_submission: true,
        entertainment: true
      }
    },
    agent: {
      type: agentType,
      autoInitialize: true
    },
    detection: {
      enabled: true,
      cooldownMinutes: 30,
      maxCasesPerDay: 3
    },
    api: {
      enabled: true,
      endpoint: 'https://api.clawtrial.app/api/v1/cases'
    }
  };

  // Ensure .clawdbot directory exists
  const clawdbotDir = path.join(process.env.HOME || '', '.clawdbot');
  if (!fs.existsSync(clawdbotDir)) {
    fs.mkdirSync(clawdbotDir, { recursive: true });
  }

  // Save config
  fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
  log('✓ Configuration saved');

  // Generate keys if needed
  const keysPath = path.join(clawdbotDir, 'courtroom_keys.json');
  if (!fs.existsSync(keysPath)) {
    log('🔑 Generating cryptographic keys...');
    try {
      // Generate Ed25519 keypair using tweetnacl
      const nacl = require('tweetnacl');
      const keyPair = nacl.sign.keyPair();
      
      const keyData = {
        publicKey: Buffer.from(keyPair.publicKey).toString('hex'),
        secretKey: Buffer.from(keyPair.secretKey).toString('hex'),
        createdAt: new Date().toISOString()
      };
      
      fs.writeFileSync(keysPath, JSON.stringify(keyData, null, 2));
      fs.chmodSync(keysPath, 0o600); // Restrict permissions
      
      log('✓ Keys generated');
      log(`📋 Public Key: ${keyData.publicKey.substring(0, 32)}...`);
      log('   (Auto-registration on first case submission)\n');
    } catch (err) {
      log('⚠️  Could not generate keys automatically.');
      log('   Run: npx courtroom-generate-keys\n');
    }
  }

  // Auto-initialize for ClawDBot
  if (isClawDBot) {
    log('🤖 Configuring for ClawDBot...');
    
    // Create auto-init script
    const initScript = `
// Auto-generated by courtroom post-install
const { createCourtroom } = require('@clawdbot/courtroom');

if (global.clawdbotAgent) {
  const courtroom = createCourtroom(global.clawdbotAgent);
  courtroom.initialize().then(() => {
    console.log('🏛️  AI Courtroom activated');
  }).catch(err => {
    console.error('Courtroom init failed:', err.message);
  });
  
  // Attach to agent
  global.clawdbotAgent.courtroom = courtroom;
}
`;
    
    const initPath = path.join(clawdbotDir, 'courtroom_auto_init.js');
    fs.writeFileSync(initPath, initScript);
    log('✓ Auto-initialization configured');
  }

  log('\n╔════════════════════════════════════════════════════════════╗');
  log('║              🎉 SETUP COMPLETE! 🎉                         ║');
  log('╠════════════════════════════════════════════════════════════╣');
  log('║                                                            ║');
  log('║  The AI Courtroom is now active!                           ║');
  log('║                                                            ║');
  log('║  Commands:                                                 ║');
  log('║    courtroom-status    - Check status                      ║');
  log('║    courtroom-disable   - Temporarily disable               ║');
  log('║    courtroom-enable    - Re-enable                         ║');
  log('║    courtroom-revoke    - Revoke consent & uninstall        ║');
  log('║    courtroom-debug     - View debug logs                   ║');
  log('║                                                            ║');
  log('║  View cases: https://clawtrial.app                         ║');
  log('╚════════════════════════════════════════════════════════════╝\n');
}

// Run if called directly
if (require.main === module) {
  postInstall().catch(err => {
    console.error('Setup failed:', err);
    process.exit(1);
  });
}

module.exports = { postInstall };
