console.log('');
console.log('🏛️  ClawTrial Courtroom v2.0.1');
console.log('   Autonomous behavioral oversight for OpenClaw agents');
console.log('');
console.log('   To use this plugin, you must install it via OpenClaw:');
console.log('   $ openclaw plugins install @clawtrial/courtroom');
console.log('');
console.log('   Then restart your gateway.');
console.log('');
console.log('   📖 Docs: https://clawtrial.app');
console.log('');
